import Card from "./MediaCard";
import "./NotSigned.css";

export const NotSigned = () => {
  return (
    <div className="not-signed">
      <h1>
        Welcome Guest
        <br />
        <br />
        You are not signed in
      </h1>
      <p>
        Sign In to explore the best games in our website "Steal.com"
        <br />
        <br />
      </p>
      <div className="cards">
        <Card  video="./Warrock.mp4"
          title="WarRock"
          cardDescription="WarRock is developed in Episodes; similar to TV programming but inverted (four seasons make up one episode). Currently WarRock is on Episode IV, Season 2 - suggesting that WarRock is in its 10th incarnation.
The game is set in the midst of a nuclear war in the fictional Republic of Derbaran. Players select between the two teams and engage in battles using 20th and 21st century military equipment, including a large assortment of infantry weapons and vehicles.[1][2] Derbaran is the government army (yellow camouflage) and NIU is the rebel army (green camouflage). During most combat modes, players are divided into these two teams and compete as an army against each other.
War Rock games are divided into six main modes of play: Conquest Mode, Capture the Base, Individual Death Match - One Man Army, Bombing Mission, Team Death Match and AI mode.[3]
Conquest Mode is a game mode where two teams fight to capture neutral bases as well as an enemy base. When the game starts, kill points of both teams will start to decrease. However, when a team has more bases captured than the other team, the rate of decrease in kill points will be slower than the other team. On the other hand, if a team has fewer bases, then the kill points decrease at a faster rate than the enemy team.
Capture the Base match begins with a neutral base in the middle. Both Derbaran and NIU teams respawn from their bases, and when any of the teams first capture the neutral base, the team occupying more bases changes to a defending team and the other team becomes a challenger. The defending team can win the match when they have successfully defended their bases for a certain period of time. Therefore, the challenging team must take over the base within the given time period.
Individual Death Match - One Man Army-Everyone fights each other until a person gets a certain number of kills and wins. Depending on the number of players in the room, small or medium size map can be selected.
Bombing Mission-The goal of this match is to bomb a selected area. Derbarans must install the bomb successfully, and NIU team must prevent the Derbarans from exploding the bomb in the designated area. Players can install/defuse the bomb by pressing the ‘F’ key. Both teams’ fate will be decided within the 3 minutes and 30 seconds of mission time.
In a Team Death Match, a team, which gets a certain number of kills wins the game. Players can respawn and enter the battlefield again when they die. Up to 32 players can connect to a War Rock game simultaneously, and players will be able to experience more excitement and intensity than any other FPS games.
In AI Mode, users fight against Bots with AI. As a player kills more bots, higher points and rank can be obtained. Kill as many bots as you can and aim for the highest points and rank!"
          image="https://th.bing.com/th/id/R.afb037990cd48b7704ffebc4ea91c984?rik=5RVbopnl4tubvA&pid=ImgRaw&r=0"
        />
     <Card video="./Gta.mp4" title="GTA San Andreas" image="https://th.bing.com/th/id/R.05b159df5861aae7beb0844507d76c61?rik=VgwzeIdLHv19dw&pid=ImgRaw&r=0" cardDescription={`Grand Theft Auto: San Andreas is a 2004 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the fifth main entry in the Grand Theft Auto series, following 2002's Grand Theft Auto: Vice City, and the seventh installment overall. It was released in October 2004 for the PlayStation 2, in June 2005 for Microsoft Windows and Xbox, and in November 2010 for Mac OS X.[2][3] The game is set within an open world environment that players can explore and interact with at their leisure. The story follows Carl "CJ" Johnson, who returns home following his mother's murder and is drawn back into his former gang and a life of crime while clashing with corrupt authorities and powerful criminals. Carl's journey takes him across the fictional U.S. state of San Andreas, which is based on California and Nevada and encompasses three major cities: Los Santos (inspired by Los Angeles), San Fierro (San Francisco) and Las Venturas (Las Vegas).[b]

The game features references to many real-life elements of the world, such as its cities, regions, and landmarks, with its plot heavily based on several real-life events in Los Angeles in the early 1990s, including the rivalry between street gangs, the crack epidemic of the 1980s and early 1990s, the LAPD Rampart scandal, and the 1992 Los Angeles riots. San Andreas introduced gameplay elements that were incorporated in later games, including role-playing-style mechanics, customisation options with both clothing and vehicle appearances, a vast array of activities and mini-games, and the inclusion of gambling games.

Considered by many reviewers to be one of the greatest video games ever made, San Andreas received critical acclaim upon release, with praise directed at its music, story and gameplay, and criticism for its graphics and some aspects of its controls. It was the best-selling video game of 2004, and with over 27.5 million copies sold worldwide as of 2011, it is the best-selling PlayStation 2 game and one of the best-selling video games of all time.[5] Like its predecessors, San Andreas is cited as a landmark in video games for its far-reaching influence within the industry. The game's violence and sexual content was the source of much public concern and controversy. In particular, a player-made software patch, dubbed the "Hot Coffee mod", unlocked a previously hidden sexual scene, resulting in the game being re-rated AO by the North American Entertainment Software Rating Board (although its previous M rating was reinstated after the game was edited to remove the content). A remastered version of the game was released for Android and iOS in 2013,[6] for Windows Phone, Fire OS and Xbox 360 in 2014, and for PlayStation 3 in 2015.[7] In June 2018, the game was made available for the Xbox One via backward compatibility. An enhanced version with the subtitle The Definitive Edition was released in 2021, and a virtual reality version for Oculus Quest 2 is in development. The next main entry in the series, Grand Theft Auto IV, was released in April 2008.`} />
     <Card video="./GTA-V.mp4" image="https://th.bing.com/th/id/R.18396ae813978728db4c5379a6dfe934?rik=vvd0yFpcNSL4vw&riu=http%3a%2f%2fwww.missinfo.tv%2fwp-content%2fuploads%2f2014%2f11%2fgta-v.jpg&ehk=EYFgg6m%2fCmNbnhxuC%2f1YlXIsXvohViQheh4u11AZ2jM%3d&risl=&pid=ImgRaw&r=0" title="GTA-V" cardDescription={`Grand Theft Auto V is a 2013 action-adventure game developed by Rockstar North and published by Rockstar Games. It is the seventh main entry in the Grand Theft Auto series, following 2008's Grand Theft Auto IV, and the fifteenth instalment overall. Set within the fictional state of San Andreas, based on Southern California, the single-player story follows three protagonists—retired bank robber Michael De Santa, street gangster Franklin Clinton, and drug dealer and gunrunner Trevor Philips—and their attempts to commit heists while under pressure from a corrupt government agency and powerful criminals. The open world design lets players freely roam San Andreas' open countryside and the fictional city of Los Santos, based on Los Angeles.

The game is played from either a third-person or first-person perspective, and its world is navigated on foot and by vehicle. Players control the three lead protagonists throughout single-player and switch among them, both during and outside missions. The story is centred on the heist sequences, and many missions involve shooting and driving gameplay. A "wanted" system governs the aggression of law enforcement response to players who commit crimes. Grand Theft Auto Online, the game's online multiplayer mode, lets up to 30 players engage in a variety of different cooperative and competitive game modes.

The game's development began around the time of Grand Theft Auto IV's release and was shared between many of Rockstar's studios worldwide. The development team drew influence from many of their previous projects such as Red Dead Redemption and Max Payne 3 and designed the game around three lead protagonists to innovate on the core structure of its predecessors. Much of the development work constituted the open world's creation, and several team members conducted field research around California to capture footage for the design team. The game's soundtrack features an original score composed by a team of producers who collaborated over several years. Grand Theft Auto V was released in September 2013 for the PlayStation 3 and Xbox 360, in November 2014 for the PlayStation 4 and Xbox One, in April 2015 for Windows, and in March 2022 for the PlayStation 5 and Xbox Series X/S.

Extensively marketed and widely anticipated, the game broke industry sales records and became the fastest-selling entertainment product in history, earning $800 million in its first day and $1 billion in its first three days. It received critical acclaim, with praise directed at its multiple protagonist design, open world, presentation and gameplay. However, it caused controversies related to its depiction of violence and women. It won year-end accolades including Game of the Year awards from several gaming publications, and is considered one of seventh and eighth generation console gaming's most significant titles and among the best video games ever made. It is the second best-selling video game of all time with over 180 million copies shipped, and as of April 2018, one of the most financially successful entertainment products of all time, with about $6 billion in worldwide revenue. Its successor is in development.`} />
      </div>
    </div>
  );
};
